/* DO NOT EDIT THIS FILE - it is machine generated */
#include
#include "../../../../../../AppData/Local/Android/sdk/ndk-bundle/platforms/android-21/arch-x86_64/usr/include/jni.h"
/* Header for class com_demo_ccalljava_JNI */

#ifndef _Included_com_demo_ccalljava_JNI
#define _Included_com_demo_ccalljava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ccalljava_JNI
 * Method:    callbackadd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_ccalljava_JNI_callbackadd
  (JNIEnv *, jobject);

/*
 * Class:     com_demo_ccalljava_JNI
 * Method:    callbacksayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_ccalljava_JNI_callbacksayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
